---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wireguard-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: 
    meta.helm.sh/release-name: wireguard
  labels:
  name: wireguard
spec:
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
      - name: wireguard
        image: linuxserver/wireguard:latest
        env:
        - name: TZ
          value: "Europe/Paris"
        - name: PEERS
          value: "32"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: ALLOWEDIPS
          value: "0.0.0.0/0"
        - name: PERSISTENTKEEPALIVE_PEERS
          value: 2,3 
        - name: SERVERPORT
          value: "51820"
        - name: SERVERURL
          value: "51.178.142.116"
        ports:
        - containerPort: 51820
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_MODULE
          privileged: true
        volumeMounts:
        - mountPath: "/config/"
          name: wireguard-config-pv

      - name: sshd
        image: dcr.sail.eyeseateam.eu/alpine-amd-sshd:0.3
        ports:
        - containerPort: 22
      imagePullSecrets:
      - name: docker-registry
      initContainers:
      - command:
        - sh
        - "-c"
        - ENI=$(ip route get 8.8.8.8 | grep 8.8.8.8 | awk '{print $5}'); sed "s/ENI/$ENI/g"
          /etc/wireguard-secret/wg0.conf.template > /config/wg0.conf; chmod 400 /config/wg0.conf; cat /config/wg0.conf
        - sysctl -w net.ipv4.ip_forward=1
        image: busybox
        name: wireguard-template-replacement
        volumeMounts:
        - mountPath: "/config/"
          name: wireguard-config-pv
        - mountPath: "/etc/wireguard-secret/"
          name: wireguard-secret
      volumes:
      - name: wireguard-config-pv
        persistentVolumeClaim:
          claimName: wireguard-config-pvc
      - name: wireguard-secret
        secret:
          secretName: wireguard

---
kind: Service
apiVersion: v1
metadata:
  name: wireguard
  labels:
    app: wireguard
spec:
  type: LoadBalancer
  ports:
  - name: wg
    protocol: UDP
    port: 51820
    targetPort: 51820
  - name: nmea
    protocol: TCP
    port: 10110
    targetPort: 10110
  - name: ssh
    protocol: TCP
    port: 23422
    targetPort: 22
  selector:
    app: wireguard
