apiVersion: v1
kind: Secret
metadata:
  name: wireguard
type: Opaque
stringData:
  wg0.conf.template: |
    [Interface]
    Address = 10.13.13.1/24
    ListenPort = 51820
    PrivateKey = yGNGOSMuxwa8dp7E5Z0ec9d4nm/OdnJYctWXv8Xwk2U=
    PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
    PostUp = sysctl -w -q net.ipv4.ip_forward=1
    PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
    PostDown = sysctl -w -q net.ipv4.ip_forward=0

    [Peer]
    PublicKey = jeTgGANRbQcwCAiWtjBMbjyvJvEPWS2PMG5u+7VCURg=
    AllowedIPs = 10.13.13.0/24
